### ISSUE TITLE
Issue with maven

### ISSUE THREAD

**Issue by Velosh** [aNNiMON/tgbots-module#11]
After `5.7.0` version, isn't possible to implement `tgbots-module` on `build.gradle` > `dependencies{}` anymore.

```
:hakalle:test: Could not find com.annimon:tgbots-module:6.1.0.
Required by:
    project :hakalle

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

Maven: https://mvnrepository.com/artifact/com.annimon/tgbots-module

**Comment by aNNiMON** [comment]
This version is not published in maven yet. I'm waiting for telegrambots 6.2.0  to be released.

**Comment by aNNiMON** [comment]
Version 6.1.0 is published one hour ago. It will be available in 4-8 hours.

**Comment by Velosh** [comment]
> Version 6.1.0 is published one hour ago. It will be available in 4-8 hours.

Thank you very much!
